services:
  ollama:
    image: ollama/ollama
    ports:
      - "5000:11434"
    volumes:
      - ollama:/root/.ollama
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  fastapi:
    build:
      context: .
    image: pyapp:latest
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app
    env_file:
      - .env
    ports:
      - "5001:8000"

  streamlit:
    build:
      context: .
    image: pyapp:latest
    command: streamlit run app.py --server.port 8501 --server.address 0.0.0.0
    volumes:
      - ./streamlit-ui:/app
    ports:
      - "5002:8501"
    
  mongodb:
    image: mongo:latest
    ports:
      - "5003:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    restart: always

  mongo-express:
    image: mongo-express
    env_file:
      - .env
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGODB_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGODB_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGODB_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGODB_PASSWORD}
    ports:
      - "5004:8081"
    depends_on:
      - mongodb
    restart: always
  
  opensearch:
    image: opensearchproject/opensearch:latest
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch
      - discovery.seed_hosts=opensearch # assuming single-node setup
      - cluster.initial_cluster_manager_nodes=opensearch
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest # Make sure the version of opensearch-dashboards matches the version of opensearch installed on other nodes
    ports:
      - 5005:5601 # Map host port 5601 to container port 5601
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch:9200"]' # Define the OpenSearch nodes that OpenSearch Dashboards will query
    
  curl:
    image: curlimages/curl:latest
    command: sleep infinity

volumes:
  ollama:
  mongodb_data:
  opensearch-data:


networks:
  default:
    name: app-network
    driver: bridge
